# Generated by Django 5.0 on 2025-08-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0014_alter_skill_options_skill_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineentry",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timelineentry",
            name="link_image",
            field=models.ImageField(
                upload_to="timeline_link_images/", blank=True, null=True
            ),
        ),
    ]
