# Generated by Django 5.0 on 2025-12-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0018_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='end_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='end_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='start_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='start_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
