# Generated by Django 5.0 on 2025-12-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0019_timelineentry_end_day_timelineentry_end_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterModelOptions(
            name='timelineentry',
            options={'ordering': ['-end_year', '-end_month', '-end_day', '-start_year', '-start_month', '-start_day', '-id']},
        ),
    ]
